version: '3'

networks:
  consul-network:
    driver: bridge
    external: false

services:

  bgps:
    image: arina/sber:master
    container_name: sber
    hostname: sber
    ports:
      - 8000:8000
    networks:
      - consul-network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/" ]
